# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

pandoc: true

sudo: required



dist: trusty

env:
    matrix:
    - BIOC_USE_DEVEL="FALSE"


before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sudo apt-get -y update -qq
  - sudo apt-get --yes install gcc-4.6-base cpp-4.6 libgomp1 libquadmath0 libc6-dev build-essential zlib1g-dev libc6-dev libcurl4-openssl-dev libxml2-dev
  - sudo apt-get --yes install curl cmake zlibc zlib1g-dev libhdf5-dev
  - sudo apt-get install -y git
  - sudo apt-get install -y pandoc
  - cwd=$(pwd) && sudo mkdir ./KallistoSource && cd ./KallistoSource && sudo git clone https://github.com/pachterlab/kallisto.git && cd ./kallisto && sudo mkdir ./build && cd ./build && sudo cmake .. && sudo make && sudo make install && cd $cwd
  - sudo echo "deb http://cran.stat.ucla.edu/bin/linux/ubuntu trusty/" >> sudo /etc/apt/sources.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update && sudo apt-get install -y r-base && sudo apt-get install -y r-base-dev && sudo apt-get update
  - sudo apt-get install -y texlive-latex-base
  - sudo apt-get install -y texlive-fonts-recommended
  - sudo apt-get install -y texlive-fonts-extra
  - sudo apt-get install -y texlive-latex-extra
install:
     - sudo ./travis-tool.sh install_bioc devtools ensembldb rtracklayer Biobase Biostrings GenomicRanges OrganismDbi Rsamtools 
    - sudo R -e 'library(devtools);install_github("arcolombo/TxDbLite")'
    - sudo ./travis-tool.sh install_bioc_deps
    - sudo ./travis-tool.sh install_bioc rhdf5 matrixStats GenomicRanges GenomicFeatures Matrix KEGGREST
    - sudo ./travis-tool.sh install_bioc rmarkdown roxygen2 knitr
    - sudo ./travis-tool.sh install_bioc RUVSeq erccdashboard pathview
    - sudo R -e 'library(devtools);install_github("arcolombo/artemis")'
    - sudo R -e 'library(devtools);install_github("arcolombo/artemisData")'
script:
    #run the vignette
     - sudo R -e 'library(rmarkdown);library(artemis);library(artemisData);render("./vignettes/artemis.Rmd")' 
     - sudo R -e 'library(rmarkdown); render("./vignettes/geneWiseAnalysis.Rmd")'
     - sudo R -e 'library(rmarkdown); render("./vignettes/pcaPlot.Rmd")'
after_failure:
  - sudo ./travis-tool.sh dump_logs
notifications:
  email:
    on_success: change
    on_failure: change
